# Generated by Django 3.2.5 on 2021-10-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltitool',
            name='deployment_ids',
        ),
    ]
