# Generated by Django 3.2.5 on 2021-10-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_user_created_in_circlein'),
        ('lti1p3_tool_config', '0002_remove_ltitool_deployment_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
