# Generated by Django 3.2.5 on 2021-10-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_user_created_in_circlein'),
        ('lti1p3_tool_config', '0003_ltitool_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lms'),
        ),
    ]
